name: citizenpower
description: Municipal Service Reporting & Accountability Platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.7
  cloud_firestore: ^4.3.1
  image_picker: ^0.8.5+3
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  connectivity_plus: ^3.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  intl: ^0.17.0
  google_maps_flutter: ^2.2.1
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.2.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/